image:
  - Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade setuptools pip"
  - "%PYTHON%\\python.exe -m pip --version"
  - "git --version"
  - "%PYTHON%\\python.exe -m pip install --upgrade .[test]"  # Installs python testing-related packages
  - "%PYTHON%\\python.exe -m pip install --upgrade -r requirements.txt"  # Gets FuzzManager, lithium-reducer from GitHub
  - "choco install codecov"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pytest --flake8 --pylint --cov-report xml setup.py src/"
  # Uncomment and replace the line above to test everything once compilation tests work on AppVeyor
  # - "%PYTHON%\\python.exe -m pytest --flake8 --pylint -p no:cov setup.py src/"
  # - "%PYTHON%\\python.exe -m pytest -p no:flake8 -p no:pylint --cov-report xml"
# on_success:
#     - "codecov -f coverage.xml"
skip_branch_with_pr: true
